In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler


In [3]:
a = np.array([[10,200, 0.3],
             [9,230, 0.1],
             [8,240, 0.24],
             [9.5, 225, 0.45]])

pa = pd.DataFrame(a,columns = ['X1', 'X2', 'X3'])
print(pa)
print()
print(f"Mean : \n{pa.mean()}\n")
print(f"Std : \n{pa.std(ddof = 0)}\n")

     X1     X2    X3
0  10.0  200.0  0.30
1   9.0  230.0  0.10
2   8.0  240.0  0.24
3   9.5  225.0  0.45

Mean : 
X1      9.1250
X2    223.7500
X3      0.2725
dtype: float64

Std : 
X1     0.739510
X2    14.737283
X3     0.125574
dtype: float64



In [4]:
scaler = StandardScaler()
scaler.fit(pa)
print(scaler.mean_)
print(scaler.scale_)

[  9.125  223.75     0.2725]
[ 0.73950997 14.73728265  0.12557368]


In [5]:
scaler.transform(pa)

array([[ 1.18321596, -1.61155897,  0.21899493],
       [-0.16903085,  0.42409446, -1.37369547],
       [-1.52127766,  1.10264561, -0.25881219],
       [ 0.50709255,  0.08481889,  1.41351273]])

In [6]:
scaler.fit_transform(pa)

array([[ 1.18321596, -1.61155897,  0.21899493],
       [-0.16903085,  0.42409446, -1.37369547],
       [-1.52127766,  1.10264561, -0.25881219],
       [ 0.50709255,  0.08481889,  1.41351273]])

# Min Max scaler

In [8]:
print(pa.min())
print(pa.max())

X1      8.0
X2    200.0
X3      0.1
dtype: float64
X1     10.00
X2    240.00
X3      0.45
dtype: float64


In [10]:
scaler = MinMaxScaler().set_output(transform = 'pandas')
scaler.fit(pa)
print(scaler.data_min_)
print(scaler.data_max_)


[8.e+00 2.e+02 1.e-01]
[ 10.   240.     0.45]


In [11]:
scaler.transform(pa)

X1     X2        X3
0  1.00  0.000  0.571429
1  0.50  0.750  0.000000
2  0.00  1.000  0.400000
3  0.75  0.625  1.000000