In [106]:
from sklearn.pipeline import Pipeline
import os
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.impute import SimpleImputer
import numpy as np
import pandas as pd
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from tqdm import tqdm
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay, classification_report, roc_curve, \
RocCurveDisplay, roc_auc_score, r2_score, mean_absolute_error
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import log_loss
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import BernoulliNB, GaussianNB
from sklearn.decomposition import PCA
from sklearn.compose import ColumnTransformer, make_column_selector


In [107]:
df = pd.read_csv('../datasets/iris.csv')
df

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [108]:
x,y = df.drop('Species', axis = 1), df['Species']
x_train,x_test, y_train, y_test = train_test_split(x,y,random_state=25, test_size=0.3, stratify=y)

In [109]:
scaler = StandardScaler().set_output(transform = 'pandas')
x_trn_scaled = scaler.fit_transform(x_train)
x_tst_scaled = scaler.transform(x_test)

In [110]:
prcomp = PCA() .set_output(transform = 'pandas')
x_trn_pca = prcomp.fit_transform(x_trn_scaled)
x_tst_pca = prcomp.transform(x_tst_scaled)

In [111]:
x_trn_pca

pca0      pca1      pca2      pca3
56   0.760325  0.787840 -0.117836  0.105107
10  -2.183062  1.054327  0.222961 -0.000453
147  1.553970  0.267171 -0.095077 -0.091468
85   0.430907  0.851371 -0.436804  0.121619
35  -2.196444 -0.259666  0.232513 -0.172358
..        ...       ...       ...       ...
145  1.900745  0.394705 -0.144339 -0.360295
74   0.749226 -0.072833  0.520798 -0.001723
134  1.270242 -0.866195  0.231651  0.516349
45  -2.047946 -0.793934  0.087576 -0.155948
11  -2.329620  0.083516 -0.129720  0.120275

[105 rows x 4 columns]

In [112]:
lr = LogisticRegression()
lr.fit(x_trn_pca.iloc[:,:2],y_train)

LogisticRegression()

In [113]:
y_pred = lr.predict(x_tst_pca.iloc[:,:2])
y_pred_proba = lr.predict_proba(x_tst_pca.iloc[:,:2])

In [114]:
print(f"Accuracy score is {accuracy_score(y_test, y_pred)}")
print(f"Log Loss is {log_loss(y_test, y_pred_proba)}")

Accuracy score is 0.8888888888888888
Log Loss is 0.20790417014553408


In [115]:
print(prcomp.explained_variance_ratio_)

[0.73081716 0.22732988 0.03654696 0.00530599]


# On HR dataset

In [116]:
hr = pd.read_csv('../datasets/HR_comma_sep.csv')
hr

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.10             0.77               6   
3                    0.92             0.85               5   
4                    0.89             1.00               5   
...                   ...              ...             ...   
14990                0.40             0.57               2   
14991                0.37             0.48               2   
14992                0.37             0.53               2   
14993                0.11             0.96               6   
14994                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  left  \
0                       157                   3              0     1   
1                       262                   6              0     1   
2                       247                   4              0     1   
3                       259                   5              0     1   
4                       224                   5              0     1   
...                     ...                 ...            ...   ...   
14990                   151                   3              0     1   
14991                   160                   3              0     1   
14992                   143                   3              0     1   
14993                   280                   4              0     1   
14994                   158                   3              0     1   

       promotion_last_5years Department  salary  
0                          0      sales     low  
1                          0      sales  medium  
2                          0      sales     low  
3                          0      sales     low  
4                          0      sales     low  
...                      ...        ...     ...  
14990                      0    support     low  
14991                      0    support     low  
14992                      0    support     low  
14993                      0    support     low  
14994                      0    support     low  

[14995 rows x 10 columns]

In [117]:
x,y = hr.drop('left',axis=1),hr['left']

In [118]:
x

satisfaction_level  last_evaluation  number_project  \
0                    0.38             0.53               2   
1                    0.80             0.86               5   
2                    0.10             0.77               6   
3                    0.92             0.85               5   
4                    0.89             1.00               5   
...                   ...              ...             ...   
14990                0.40             0.57               2   
14991                0.37             0.48               2   
14992                0.37             0.53               2   
14993                0.11             0.96               6   
14994                0.37             0.52               2   

       average_montly_hours  time_spend_company  Work_accident  \
0                       157                   3              0   
1                       262                   6              0   
2                       247                   4              0   
3                       259                   5              0   
4                       224                   5              0   
...                     ...                 ...            ...   
14990                   151                   3              0   
14991                   160                   3              0   
14992                   143                   3              0   
14993                   280                   4              0   
14994                   158                   3              0   

       promotion_last_5years Department  salary  
0                          0      sales     low  
1                          0      sales  medium  
2                          0      sales     low  
3                          0      sales     low  
4                          0      sales     low  
...                      ...        ...     ...  
14990                      0    support     low  
14991                      0    support     low  
14992                      0    support     low  
14993                      0    support     low  
14994                      0    support     low  

[14995 rows x 9 columns]

In [119]:
ohe = OneHotEncoder(drop = 'first', sparse_output=False).set_output(transform = 'pandas')
col_trnf = ColumnTransformer([('OHE', ohe, make_column_selector(dtype_include = object ))],
                             remainder = 'passthrough',
                             verbose_feature_names_out=False)
col_trnf = col_trnf.set_output(transform = 'pandas')

x = col_trnf.fit_transform(x)

In [120]:
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=25, stratify=y, test_size=0.3)

In [121]:
scaler = StandardScaler()

x_scaled = scaler.fit_transform(x)

In [122]:
pca = PCA().set_output(transform = 'pandas')
x_pca = pca.fit_transform(x_scaled)
x_pca

pca0      pca1      pca2      pca3      pca4      pca5      pca6  \
0      2.062567 -1.277916  1.717324 -0.407256 -0.415048 -0.683604 -0.462609   
1     -2.179013  1.349868  1.805659 -0.815077  0.074271  0.273313 -0.161111   
2      0.706111  2.354919  1.783871 -0.669350 -0.469326 -1.362388 -0.459271   
3      0.535807  2.095005  1.782238 -0.607931  0.209973  0.852616  0.089689   
4      0.514096  2.162069  1.751595 -0.601606  0.259402  0.937999  0.113467   
...         ...       ...       ...       ...       ...       ...       ...   
14990  2.055157 -1.169195 -0.867163  0.354286  1.670129 -0.984599 -1.488942   
14991  2.120475 -1.311012 -0.842726  0.383258  1.588231 -1.178297 -1.553500   
14992  2.132981 -1.347275 -0.853910  0.394984  1.607220 -1.131034 -1.546063   
14993  0.385333  3.275771 -0.836345 -0.059983  1.760778 -1.422809 -1.344272   
14994  2.085110 -1.221880 -0.852104  0.368287  1.615817 -1.124376 -1.531311   

           pca7      pca8      pca9     pca10     pca11     pca12     pca13  \
0     -0.006399 -0.050662 -0.060590 -0.389617 -0.106237  0.034951 -0.110121   
1      0.180962  0.159711  0.038900  0.096511 -0.351920 -0.382442  1.098338   
2     -0.228243 -0.073131 -0.063603 -0.886503  0.334819  0.299897 -0.835835   
3      0.079989  0.134855  0.186052  0.448072 -0.588016 -0.201605  0.808754   
4      0.095813  0.165425  0.202280  0.528559 -0.663100 -0.271522  1.005344   
...         ...       ...       ...       ...       ...       ...       ...   
14990  0.067859 -0.044901 -0.090637 -0.560558 -0.186800  0.316670  0.189808   
14991  0.058610 -0.077438 -0.121514 -0.688976 -0.087723  0.359479  0.073497   
14992  0.072401 -0.068029 -0.116970 -0.649808 -0.121823  0.324218  0.177559   
14993 -0.213735  0.002044 -0.022197 -0.905219  0.137425  0.615076 -0.682423   
14994  0.056955 -0.064375 -0.110075 -0.651194 -0.118237  0.348709  0.099180   

          pca14     pca15     pca16     pca17  
0      0.101194 -0.617137  0.073648  0.080859  
1     -0.542182  0.069501  0.094916  0.089874  
2      0.213604  0.284613  0.047177  0.081986  
3     -0.634701  0.332310  0.094717  0.091833  
4      0.460779  0.341190  0.079849  0.087717  
...         ...       ...       ...       ...  
14990  0.194737 -0.618271  0.071155  0.093884  
14991 -0.256192 -0.571559  0.076969  0.094996  
14992  0.165408 -0.508423  0.072522  0.093480  
14993  0.440799 -0.354885  0.032330  0.095217  
14994 -0.066156 -0.626217  0.073616  0.094415  

[14995 rows x 18 columns]

In [123]:
np.cumsum(pca.explained_variance_ratio_ * 100)

array([ 10.42723133,  20.58793491,  27.95567097,  34.76490283,
        41.43340638,  47.76274027,  53.86705251,  59.78971986,
        65.6726812 ,  71.52370417,  77.29664846,  82.69834762,
        87.55599268,  92.10660041,  95.62030665,  98.658159  ,
        99.46053041, 100.        ])

In [ ]:
lr = LogisticRegression()
scores = []
for n in np.arange(8,17):
    # lr.fit_transform(x_pca.iloc[:,:n], y_)
    # print(n)
    prcomp = PCA(n_components=n).set_output(transform = 'pandas')
    pipe = Pipeline([('Scaling', scaler), ('PCA', prcomp), ('Logistic Regression', lr)])
    pipe.fit(x_train, y_train)
    y_pred_proba = pipe.predict_proba(x_test)
    y_pred = pipe.predict(x_test)

    scores.append([n, log_loss(y_test, y_pred_proba), accuracy_score(y_test, y_pred)])

scores_Df = pd.DataFrame(data = scores, columns = ['No. of components', 'Log Loss', 'Accuracy'])
scores_Df.sort_values('Log Loss', ascending=True)

8
9
10
11
12
13
14
15
16


No. of components  Log Loss  Accuracy
8                 16  0.435271  0.786397
7                 15  0.453500  0.773505
6                 14  0.454651  0.773727
5                 13  0.455281  0.773283
4                 12  0.455287  0.773283
3                 11  0.457279  0.774394
2                 10  0.469994  0.781507
1                  9  0.470455  0.782396
0                  8  0.471058  0.777728

using percentage n_components as pecentage

In [134]:
lr = LogisticRegression()
scores = []
for n in np.linspace(0.5, 0.95, 15):
    prcomp = PCA(n_components=n).set_output(transform = 'pandas')
    pipe = Pipeline([('Scaling', scaler), ('PCA', prcomp), ('Logistic Regression', lr)])
    pipe.fit(x_train, y_train)
    y_pred_proba = pipe.predict_proba(x_test)
    y_pred = pipe.predict(x_test)

    scores.append([n*100, log_loss(y_test, y_pred_proba), accuracy_score(y_test, y_pred)])

scores_Df = pd.DataFrame(data = scores, columns = ['precentage variance', 'Log Loss', 'Accuracy'])
scores_Df.sort_values('Log Loss', ascending=True)

precentage variance  Log Loss  Accuracy
14            95.000000  0.453500  0.773505
12            88.571429  0.454651  0.773727
13            91.785714  0.454651  0.773727
11            85.357143  0.455281  0.773283
10            82.142857  0.455287  0.773283
9             78.928571  0.455287  0.773283
7             72.500000  0.457279  0.774394
8             75.714286  0.457279  0.774394
5             66.071429  0.469994  0.781507
6             69.285714  0.469994  0.781507
4             62.857143  0.470455  0.782396
2             56.428571  0.471058  0.777728
3             59.642857  0.471058  0.777728
0             50.000000  0.471620  0.779284
1             53.214286  0.471620  0.779284

In [128]:
np.cumsum(prcomp.explained_variance_ratio_*100)

array([10.40178671, 20.54642315, 27.89502036, 34.7204589 , 41.41037659,
       47.7757818 , 53.87157964, 59.78241706, 65.66220656, 71.51420384,
       77.2483374 , 82.68393776, 87.52473423, 92.08268613, 95.61509879])

In [132]:
pipe['PCA'].explained_variance_ratio_

array([0.10401787, 0.10144636, 0.07348597, 0.06825439, 0.06689918,
       0.06365405, 0.06095798, 0.05910837, 0.0587979 , 0.05851997,
       0.05734134, 0.054356  , 0.04840796, 0.04557952, 0.03532413])