In [22]:
import pandas as pd
from sklearn.linear_model import Ridge, Lasso, ElasticNet, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
import numpy as np
import os
winconsin = pd.read_csv("D:/Machine Learning/Cases/Wisconsin/BreastCancer.csv", index_col=0)
winconsin

Clump  UniCell_Size  Uni_CellShape  MargAdh  SEpith  BareN  \
Code                                                                   
61634         5             4              3        1       2      2   
63375         9             1              2        6       4     10   
76389        10             4              7        2       2      8   
95719         6            10             10       10       8     10   
128059        1             1              1        1       2      5   
...         ...           ...            ...      ...     ...    ...   
1369821      10            10             10       10       5     10   
1371026       5            10             10       10       4     10   
1371920       5             1              1        1       2      1   
8233704       4             1              1        1       1      1   
13454352      1             1              3        1       2      1   

          BChromatin  NoemN  Mitoses      Class  
Code                                             
61634              2      3        1     Benign  
63375              7      7        2  Malignant  
76389              6      1        1  Malignant  
95719              7     10        7  Malignant  
128059             5      1        1     Benign  
...              ...    ...      ...        ...  
1369821           10     10        7  Malignant  
1371026            5      6        3  Malignant  
1371920            3      2        1     Benign  
8233704            2      1        1     Benign  
13454352           2      1        1     Benign  

[699 rows x 10 columns]

In [7]:
le = LabelEncoder()
winconsin['Class'] = le.fit_transform(winconsin['Class'])
winconsin

Clump  UniCell_Size  Uni_CellShape  MargAdh  SEpith  BareN  \
Code                                                                   
61634         5             4              3        1       2      2   
63375         9             1              2        6       4     10   
76389        10             4              7        2       2      8   
95719         6            10             10       10       8     10   
128059        1             1              1        1       2      5   
...         ...           ...            ...      ...     ...    ...   
1369821      10            10             10       10       5     10   
1371026       5            10             10       10       4     10   
1371920       5             1              1        1       2      1   
8233704       4             1              1        1       1      1   
13454352      1             1              3        1       2      1   

          BChromatin  NoemN  Mitoses  Class  
Code                                         
61634              2      3        1      0  
63375              7      7        2      1  
76389              6      1        1      1  
95719              7     10        7      1  
128059             5      1        1      0  
...              ...    ...      ...    ...  
1369821           10     10        7      1  
1371026            5      6        3      1  
1371920            3      2        1      0  
8233704            2      1        1      0  
13454352           2      1        1      0  

[699 rows x 10 columns]

In [8]:
le.classes_

array([0, 1])

In [9]:
x,y = winconsin.drop('Class', axis=1), winconsin['Class']
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state = 42, stratify=y)

In [13]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.predict_proba(x_test)
lr.intercept_, lr.coef_

(array([-9.30439406]),
 array([[ 0.51531437, -0.09204887,  0.41867343,  0.28028088, -0.0618495 ,
          0.35292056,  0.4646252 ,  0.2101526 ,  0.52916133]]))

In [15]:
lr.predict_proba(x_test)

array([[9.98377866e-01, 1.62213445e-03],
       [9.96725743e-01, 3.27425656e-03],
       [9.98138275e-01, 1.86172497e-03],
       [2.09874308e-02, 9.79012569e-01],
       [7.14643330e-01, 2.85356670e-01],
       [9.65770297e-01, 3.42297028e-02],
       [9.97299641e-01, 2.70035860e-03],
       [9.96852247e-01, 3.14775310e-03],
       [9.90542514e-01, 9.45748550e-03],
       [9.90876678e-01, 9.12332219e-03],
       [9.60844276e-01, 3.91557243e-02],
       [9.97040477e-01, 2.95952330e-03],
       [3.83044588e-02, 9.61695541e-01],
       [9.91323694e-01, 8.67630605e-03],
       [4.51455842e-04, 9.99548544e-01],
       [9.95214326e-01, 4.78567375e-03],
       [9.83866498e-01, 1.61335025e-02],
       [9.96887073e-01, 3.11292722e-03],
       [9.86262863e-01, 1.37371366e-02],
       [9.73708850e-01, 2.62911503e-02],
       [9.97040477e-01, 2.95952330e-03],
       [1.02123138e-04, 9.99897877e-01],
       [9.78228933e-01, 2.17710674e-02],
       [6.90519257e-02, 9.30948074e-01],
       [9.861375

In [23]:
y_pred = lr.predict(x_test)
y_pred

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0])

In [24]:
conf = confusion_matrix(y_test,y_pred)
print(conf)

acc = accuracy_score(y_test, y_pred)
acc

[[136   2]
 [  2  70]]


0.9809523809523809

#### Classifier is a probablity function