In [25]:
import pandas as pd
from sklearn.linear_model import Ridge, Lasso, ElasticNet, LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.compose import make_column_selector
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
import numpy as np
import os
winconsin = pd.read_csv("D:/Machine Learning/Cases/Wisconsin/BreastCancer.csv", index_col=0)
winconsin

Clump  UniCell_Size  Uni_CellShape  MargAdh  SEpith  BareN  \
Code                                                                   
61634         5             4              3        1       2      2   
63375         9             1              2        6       4     10   
76389        10             4              7        2       2      8   
95719         6            10             10       10       8     10   
128059        1             1              1        1       2      5   
...         ...           ...            ...      ...     ...    ...   
1369821      10            10             10       10       5     10   
1371026       5            10             10       10       4     10   
1371920       5             1              1        1       2      1   
8233704       4             1              1        1       1      1   
13454352      1             1              3        1       2      1   

          BChromatin  NoemN  Mitoses      Class  
Code                                             
61634              2      3        1     Benign  
63375              7      7        2  Malignant  
76389              6      1        1  Malignant  
95719              7     10        7  Malignant  
128059             5      1        1     Benign  
...              ...    ...      ...        ...  
1369821           10     10        7  Malignant  
1371026            5      6        3  Malignant  
1371920            3      2        1     Benign  
8233704            2      1        1     Benign  
13454352           2      1        1     Benign  

[699 rows x 10 columns]

In [26]:
le = LabelEncoder()
winconsin['Class'] = le.fit_transform(winconsin['Class'])
winconsin

Clump  UniCell_Size  Uni_CellShape  MargAdh  SEpith  BareN  \
Code                                                                   
61634         5             4              3        1       2      2   
63375         9             1              2        6       4     10   
76389        10             4              7        2       2      8   
95719         6            10             10       10       8     10   
128059        1             1              1        1       2      5   
...         ...           ...            ...      ...     ...    ...   
1369821      10            10             10       10       5     10   
1371026       5            10             10       10       4     10   
1371920       5             1              1        1       2      1   
8233704       4             1              1        1       1      1   
13454352      1             1              3        1       2      1   

          BChromatin  NoemN  Mitoses  Class  
Code                                         
61634              2      3        1      0  
63375              7      7        2      1  
76389              6      1        1      1  
95719              7     10        7      1  
128059             5      1        1      0  
...              ...    ...      ...    ...  
1369821           10     10        7      1  
1371026            5      6        3      1  
1371920            3      2        1      0  
8233704            2      1        1      0  
13454352           2      1        1      0  

[699 rows x 10 columns]

In [27]:
le.classes_

array(['Benign', 'Malignant'], dtype=object)

In [28]:
x,y = winconsin.drop('Class', axis=1), winconsin['Class']
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state = 25, stratify=y)

In [29]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.predict_proba(x_test)
lr.intercept_, lr.coef_

(array([-10.13685623]),
 array([[ 0.54707603,  0.04474491,  0.20952885,  0.19219542, -0.00722953,
          0.39656381,  0.60692755,  0.19441253,  0.53085196]]))

In [30]:
lr.predict_proba(x_test)

array([[9.98120767e-01, 1.87923285e-03],
       [9.98229749e-01, 1.77025092e-03],
       [1.96481629e-04, 9.99803518e-01],
       [9.82482033e-01, 1.75179672e-02],
       [9.94408267e-01, 5.59173308e-03],
       [5.51665724e-01, 4.48334276e-01],
       [2.05397996e-03, 9.97946020e-01],
       [9.76178351e-01, 2.38216491e-02],
       [9.98597104e-01, 1.40289575e-03],
       [9.96557412e-01, 3.44258849e-03],
       [9.99275706e-01, 7.24293521e-04],
       [9.98134279e-01, 1.86572114e-03],
       [5.46197681e-04, 9.99453802e-01],
       [9.89788038e-01, 1.02119620e-02],
       [9.89788038e-01, 1.02119620e-02],
       [9.98903064e-01, 1.09693596e-03],
       [1.16178478e-01, 8.83821522e-01],
       [9.98911740e-01, 1.08825963e-03],
       [9.98911740e-01, 1.08825963e-03],
       [9.90375598e-01, 9.62440163e-03],
       [9.96542540e-01, 3.45746032e-03],
       [7.31077129e-01, 2.68922871e-01],
       [4.51767821e-04, 9.99548232e-01],
       [4.26536006e-02, 9.57346399e-01],
       [9.958841

In [31]:
y_pred = lr.predict(x_test)
y_pred

array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0])

In [32]:
conf = confusion_matrix(y_test,y_pred)
print(conf)

acc = accuracy_score(y_test, y_pred)
acc

[[137   1]
 [  6  66]]


0.9666666666666667

#### Classifier is a probablity function